### ISSUE TITLE
`isTrigger` prop not implemented

### ISSUE THREAD

**Issue by mklasinc** [pmndrs/use-p2#1]
### Problem
The documentation says an `isTrigger` prop can be passed to the body to make it work as a collision detection trigger (similarly to how `cannon-es`, `use-cannon` work following this [PR](https://github.com/pmndrs/cannon-es/pull/83).

However, `p2-es` does not implement an `isTrigger` prop anywhere in the codebase.
You can instead pass the `sensor` boolean when instantiating a shape ([codebase ref](https://github.com/pmndrs/p2-es/blob/master/src/shapes/Shape.js#L16), but the current implementation off `use-p2` doesn't allow to pass extra props to shapes.

### Solution?
Add ability to pass extra props to shapes when creating a body or implement the `isTrigger` prop.

Also here's the [p2.js sensor demo](http://schteppe.github.io/p2.js/examples/canvas/sensors.html)

**Comment by joergjaeckel** [comment]
Will take a look, meanwhile you can set collisionResponse false like in the example https://github.com/pmndrs/use-p2/blob/main/examples/src/demos/PhysicalCharacterController/Heart.tsx#L55

**Comment by joergjaeckel** [comment]
You can use it now as expected. Set an isTrigger prop to the body, it will set the sensor prop on each shape of the body. See examples/src/demos/Trigger.tsx

**Comment by mklasinc** [comment]
Super, thanks for the quick action!
