### ISSUE TITLE
how to rotate a body smoothly?

### ISSUE THREAD

**Issue by AmirHo3einJS** [pmndrs/use-p2#15]
Hello, So I want to set the angle of a body smoothly. for instance from 0 to 90 degrees. how can I do that? I wanted to use angular velocity or apply torque to the body but there is no ensure that the final angle of the body would be 90 degrees.

**Comment by isaac-mason** [comment]
Closing this issue, see the discussion on the p2-es repo: https://github.com/pmndrs/p2-es/discussions/17
