### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by amilajack** [pmndrs/use-p2#6]
The demo site (https://p2.pmnd.rs/) seems to be down. Happy to PR a fix if possible

**Comment by joergjaeckel** [comment]
Would be happy to see it, too! It was never up running 😉 Might need your help @drcmda with the subdomain. The same automatic deployment setup like use-cannon would be helpful.

**Comment by isaac-mason** [comment]
The demo site is up now :)

https://p2.pmnd.rs/
